In [1]:
import numpy as np

In [7]:
array = np.arange(15).reshape(3, 5)

In [8]:
array.shape

(3, 5)

In [9]:
array.ndim

2

In [10]:
array.dtype.name

'int64'

In [12]:
array.itemsize

8

In [13]:
array.size

15

In [14]:
type(array)

numpy.ndarray

In [15]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [16]:
np.arange(10000).reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [17]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
a-b

array([20, 29, 38, 47])

In [18]:
b**2

array([0, 1, 4, 9])

In [19]:
a<35

array([ True,  True, False, False])

In [20]:
a = np.array([[1,1], [0,1]])
b = np.array([[2,0], [3,4]])
a*b

array([[2, 0],
       [0, 4]])

In [21]:
a@b

array([[5, 4],
       [3, 4]])

In [22]:
b@a

array([[2, 2],
       [3, 7]])

In [23]:
a@b-b@a

array([[ 3,  2],
       [ 0, -3]])

In [24]:
b@a-a@b

array([[-3, -2],
       [ 0,  3]])

In [26]:
np.random.random((2,3))

array([[0.13633655, 0.59504603, 0.20786645],
       [0.98237393, 0.54356547, 0.95603366]])

In [27]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [29]:
b.sum(axis=1)

array([ 6, 22, 38])

In [31]:
b.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [32]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [33]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [34]:
a[2]

8

In [35]:
a[2:5]

array([ 8, 27, 64])

In [36]:
a[:6:2]

array([ 0,  8, 64])

In [37]:
a[:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [38]:
def f(x,y):
    return 10*x + y

b = np.fromfunction(f, (5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [43]:
a = np.floor(10*np.random.random((3,4)))
a

array([[7., 8., 6., 8.],
       [7., 2., 5., 3.],
       [8., 7., 1., 7.]])

In [44]:
a.shape

(3, 4)

In [45]:
a.ravel()

array([7., 8., 6., 8., 7., 2., 5., 3., 8., 7., 1., 7.])

In [46]:
a.reshape(6,2)

array([[7., 8.],
       [6., 8.],
       [7., 2.],
       [5., 3.],
       [8., 7.],
       [1., 7.]])

In [47]:
a.T

array([[7., 7., 8.],
       [8., 2., 7.],
       [6., 5., 1.],
       [8., 3., 7.]])

In [48]:
a.resize(2,6)

In [49]:
a

array([[7., 8., 6., 8., 7., 2.],
       [5., 3., 8., 7., 1., 7.]])

In [50]:
a.reshape(3,-1)

array([[7., 8., 6., 8.],
       [7., 2., 5., 3.],
       [8., 7., 1., 7.]])

In [52]:
a = np.floor(10*np.random.random((2,2)))
a

array([[8., 8.],
       [5., 1.]])

In [53]:
b = np.floor(10*np.random.random((2,2)))
b

array([[8., 9.],
       [9., 6.]])

In [54]:
np.vstack((a,b))

array([[8., 8.],
       [5., 1.],
       [8., 9.],
       [9., 6.]])

In [55]:
np.hstack((a,b))

array([[8., 8., 8., 9.],
       [5., 1., 9., 6.]])

In [56]:
np.column_stack((a,b))

array([[8., 8., 8., 9.],
       [5., 1., 9., 6.]])

In [57]:
from numpy import newaxis
a[:,newaxis]

array([[[8., 8.]],

       [[5., 1.]]])

In [58]:
np.column_stack((a[:,newaxis], b[:,newaxis]))

array([[[8., 8.],
        [8., 9.]],

       [[5., 1.],
        [9., 6.]]])

In [59]:
a = np.floor(10*np.random.random((2,12)))
a

array([[1., 6., 7., 7., 8., 8., 9., 2., 9., 5., 7., 4.],
       [7., 2., 3., 6., 4., 2., 8., 3., 8., 2., 8., 0.]])

In [60]:
np.hsplit(a,3)

[array([[1., 6., 7., 7.],
        [7., 2., 3., 6.]]), array([[8., 8., 9., 2.],
        [4., 2., 8., 3.]]), array([[9., 5., 7., 4.],
        [8., 2., 8., 0.]])]

In [61]:
np.hsplit(a, (3,4))

[array([[1., 6., 7.],
        [7., 2., 3.]]), array([[7.],
        [6.]]), array([[8., 8., 9., 2., 9., 5., 7., 4.],
        [4., 2., 8., 3., 8., 2., 8., 0.]])]